name: CIfixedVersions

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Permssions
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  
jobs:
    test_fixed_versions:
      runs-on: ubuntu-22.04

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies at fixed version
        run: |
          pip install numpy==1.25.0 scipy==1.12.0 qutip==5.0.0 sympy==1.11 numba==0.58.0 pytest ipython tk
          pip install .

      - name: Run tests and coverage
        run: |
          python simos/test/report_versions.py
          pytest --junitxml=report.xml
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: report.xml