name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel twine qutip sympy numpy pytest numba scipy ipython tk setuptools
    
    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
      
      
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: ${{ !github.event.release.prerelease }}
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: ${{ github.event.release.prerelease }}
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
